apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-deployment
  namespace: workshop
  labels:
    app: customer-service
    tags.datadoghq.com/service: customer-service
    tags.datadoghq.com/env: development
    tags.datadoghq.com/version: "1.0.0"
spec:
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
        tags.datadoghq.com/service: customer-service
        tags.datadoghq.com/env: development
        tags.datadoghq.com/version: "1.0.0"
      annotations:
        ad.datadoghq.com/web.logs: |
          [
            {
              "source": "ruby",
              "service": "customer-service"
            }
          ]
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: customer-service
          image: "${IMAGE_URI}"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DD_TRACE_HTTP_CLIENT_IGNORE_URLS
              value: "/up"
            - name: DD_TRACE_ENABLED
              value: "true"
            - name: DD_AGENT_HOST
              value: datadog-agent
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_TRACE_HTTP_CLIENT_IGNORE_URLS
              value: "/up"
            - name: RAILS_LOG_TO_STDOUT
              value: "true"
            - name: UID
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: UID
            - name: GID
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: GID
            - name: DATABASE_HOST
              value: db-customer-service
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: DATABASE_PASSWORD
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: SECRET_KEY_BASE
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /up
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /up
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 60
      restartPolicy: Always
