name: Deploy App

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    env:
      K8S_NAMESPACE: workshop

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          TAG="$(date +'%Y%m%d-%H%M%S')-${GITHUB_SHA::7}"
          IMAGE="ghcr.io/${{ github.repository }}:$TAG"
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE_URI=$IMAGE" >> $GITHUB_ENV

      - name: Render manifests
        env:
          IMAGE_URI: ${{ env.IMAGE_URI }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
        run: |
          envsubst < infra/k8s/customer-service-deployment.tmpl.yaml > infra/k8s/customer-service-deployment.yaml
          envsubst < infra/k8s/web-secret.tmpl.yaml > infra/k8s/web-secret.yaml

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - run: terraform -chdir=infra/terraform init -input=false
      - run: terraform -chdir=infra/terraform apply -auto-approve

      - name: Wait for deployment rollout
        run: |
           kubectl rollout status deployment/customer-service-deployment --timeout=140s -n $K8S_NAMESPACE
